# Generated by Django 4.0.5 on 2022-07-04 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dogs',
            table='Dogs',
        ),
        migrations.AlterModelTable(
            name='owners',
            table='Owners',
        ),
    ]
