# Generated by Django 4.0.5 on 2022-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_actors_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='movies',
            field=models.ManyToManyField(related_name='movies', to='movies.movies'),
        ),
    ]
